config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # READ
  root 'tasks#index'

    #CREATE
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#creato'

  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: 'task'

  #UPDATE
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'

  #DELETE
  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index #view
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def creato
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :difficulty, :duration, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :difficulty %>
  <%= f.number_field :difficulty %>

  <%= f.label :duration %>
  <%= f.number_field :duration %>

  <%= f.label :done %>
  <%= f.check_box :done? %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks:</h1>

<%= link_to "New task", tasks_new_path  %>

<ul>
  <% @tasks.each do |task| %>
  <li>
    <h2><%= link_to task.name, task_path(task) %></h2>
    <p><%= link_to "Delete task", task_path(task), method: :delete %></p>
  </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%=  @task.name %> </h1>

<p>Difficulty: <%= "*" * @task.difficulty %></p>
<p>Duration: <%= @task.duration %> minutes</p>
<p>Done? <%= @task.done %></p>

<%= link_to "Back to tasks", root_path %>
<%= link_to "Edit task", task_edit_path %>